version: "3.8"

services:
  app:
    container_name: admin-dashboard
    build: .
    ports:
      - "3001:80" # Maps port 80 of the container to port 80 on the host
    restart: always # Ensures the container restarts on failures
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount a custom Nginx config if needed
    restart: always
